### ISSUE TITLE
Proper Semantic Versioning

### ISSUE THREAD

**Issue by bdwyertech** [ruby/rexml#131]
@kou @nobu, the two most recent releases 3.2.7 and 3.2.8 should be major versions as they introduce `strscan` which seems to require some native extensions and compilation on systems.  This is breaking my world with folks using Chef.  Can you please yank those and make this 4.x.x or something?

For Chef folks looking for a fix, add the following to your cookbooks metadata.rb:
```ruby
# Temporary Workaround (https://github.com/ruby/rexml/issues/131)
gem 'rexml', '= 3.2.6'
```

You can also install `gcc` in your kitchen using:
```yaml
lifecycle:
  post_create:
    # Temporary Workaround (https://github.com/ruby/rexml/issues/131)
    - remote: sudo yum install -y gcc
 ```

Thanks
